---
title: Configuration
description: Applies some LightOS configurations
privilege: TrustedInstaller
actions:

  # Disable transparency and animations for low end devices
  - !powerShell:
    runas: currentUserElevated
    command: |
      $mem = (Get-CimInstance Win32_PhysicalMemory | Measure-Object Capacity -Sum).Sum
      if ($mem -lt 9000000000) {
        [microsoft.win32.registry]::SetValue('HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize', 'EnableTransparency', 0, [Microsoft.Win32.RegistryValueKind]::DWord)
        [microsoft.win32.registry]::SetValue('HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics', 'MinAnimate', 0, [Microsoft.Win32.RegistryValueKind]::DWord)
      }

  # Disable Memory Compression
  - !powerShell: 
    command: 'Disable-MMAgent -mc'

  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Services\Pending\7971f918-a847-4430-9279-4a52d1efe18d', value: 'RegisterWithAU', type: REG_DWORD, data: '0'}
  
  
  - !cmd:
    command: 'setx DOTNET_CLI_TELEMETRY_OPTOUT 1'
    runas: currentUserElevated
    
  - !cmd:
    command: 'setx POWERSHELL_TELEMETRY_OPTOUT 1'
    runas: currentUserElevated

  - !writeStatus: {status: "Removing logs"}
  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File CLEANER.ps1'
    weight: 150

  - !writeStatus: {status: "Finalizing process"}
  - !registryValue: {path: 'HKCU\System\GameConfigStore', value: 'GameDVR_FSEBehaviorMode', type: REG_DWORD, data: '0', weight: 70}

  - !powerShell: {command: 'Get-ScheduledTask -TaskPath "\Microsoft\Office\*" | Disable-ScheduledTask'}

  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File SVCGROUP.ps1'
    weight: 50

  - !run: {exeDir: true, exe: "FINALIZE.cmd", weight: 200}

  - !run:
    exeDir: true
    exe: "STARTMENU.cmd"
    option: "remove-pinned-items-startmenu"
    weight: 100

  - !run:
    exeDir: true
    exe: "WD.bat"
    option: "disable-defender"
    weight: 100

  - !run:
    exeDir: true
    exe: "FILEASSOC.cmd"
    option: "remove-appx-photos"
    weight: 150

  # Necessary to refresh start menu entries etc.
  - !appx: {operation: clearCache, name: '*Client.CBS*'}
  - !appx: {operation: clearCache, name: '*StartMenuExperienceHost*', option: "remove-pinned-items-startmenu"}
  - !appx: {operation: clearCache, name: '*Windows.Search*'}
  - !appx: {operation: clearCache, name: '*TCUI*'}

  # Force update group policy
  - !run: 
    exe: "gpupdate.exe"
    
  - !powerShell:
    command: |
      $explorerProcess = Get-Process -Name explorer -ErrorAction SilentlyContinue
      if ($explorerProcess) {
        Stop-Process -Name explorer -Force
      }
      Start-Process explorer
    runas: currentUserElevated
